# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('w_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('w_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('w_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_task', to='task.Task', verbose_name='Task')),
            ],
        ),
    ]
