# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('t_name', models.CharField(max_length=120, verbose_name='Name')),
                ('t_defination', models.TextField(verbose_name='Defination')),
                ('t_begin', models.DateTimeField(auto_now_add=True, verbose_name='Begin Date')),
                ('t_end', models.DateTimeField(verbose_name='End Date')),
                ('t_status', models.IntegerField(default=0, verbose_name='Status')),
                ('t_slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('t_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_project', to='project.Project', verbose_name='Project')),
            ],
            options={
                'ordering': ['t_name', 't_id'],
            },
        ),
    ]
