# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('p_name', models.CharField(max_length=120, verbose_name='Name')),
                ('p_defination', models.TextField(verbose_name='Defination')),
                ('p_type', models.CharField(max_length=120, verbose_name='Type')),
                ('p_begin', models.DateTimeField(verbose_name='Begin Date')),
                ('p_end', models.DateTimeField(verbose_name='End Date')),
                ('p_status', models.IntegerField(default=0, verbose_name='Status')),
                ('p_slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('p_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_manager', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'ordering': ['p_name', 'p_id'],
            },
        ),
    ]
